const words = [
    { word: "JAVASCRIPT", hint: "A programming language for web development" },
    { word: "HANGMAN", hint: "A popular word-guessing game" },
    { word: "PROGRAMMING", hint: "The process of writing computer code" },
    { word: "DEVELOPER", hint: "A person who writes software" },
    { word: "COMPUTER", hint: "An electronic device for processing data" },
    { word: "SOFTWARE", hint: "Programs used by a computer" },
    { word: "HARDWARE", hint: "The physical components of a computer" },
    { word: "ALGORITHM", hint: "A step-by-step procedure for calculations" },
    { word: "NETWORK", hint: "A system of interconnected computers" },
    { word: "INTERNET", hint: "A global network connecting devices" },
    { word: "GUITAR", hint: "A musical instrument with strings." },
    { word: "OXYGEN", hint:"A colorless, odorless gas essential for life." },
    { word: "MOUNTAIN", hint:  "A large natural elevation of the Earth's surface." },
    { word: "PAINTING", hint:"An art form using colors on a surface to create images or expression."  },
    { word: "ASTRONOMY", hint:"The scientific study of celestial objects and phenomena."},
    { word: "FOOTBALL", hint: "A popular sport played with a spherical ball." },
    { word: "CHOCOLTE", hint:"A sweet treat made from cocoa beans."  },
    { word: "BUTTERFLY", hint:"An insect with colorful wings and a slender body." },
    { word: "HISTORY", hint:"The study of past events and human civilization." },
    { word: "PIZZA", hint:"A savory dish consisting of a round, flattened base with toppings."},
    { word: "JAZZ", hint: "A genre of music characterized by improvisation and syncopation."},
    { word: "CAMERA", hint: "A device used to capture and record images or videos." },
    { word: "DIAMOND", hint: "A precious gemstone known for its brilliance and hardness." },
    { word: "ADEVENTURE", hint: "An exciting or daring experience." },
    { word: "BICYCLE", hint:"A human-powered vehicle with two wheels." },
    { word: "SUNSET" , hint: "The daily disappearance of the sun below the horizon." },
    { word:  "coffee", hint:  "A popular caffeinated beverage made from roasted coffee beans."},
    { word: "dance" , hint:  "A rhythmic movement of the body often performed to music."},
    { word:  "galaxy" , hint: "A vast system of stars, gas, and dust held together by gravity." },
    { word: "orchestra" , hint: "A large ensemble of musicians playing various instruments."},
    { word: "volcano" , hint: "A mountain or hill with a vent through which lava, rock fragments, hot vapor, and gas are ejected." },
    { word:  "novel", hint: "A long work of fiction, typically with a complex plot and characters."},
    { word: "sculpture", hint:  "A three-dimensional art form created by shaping or combining materials."},
    { word: "symphony" , hint: "A long musical composition for a full orchestra, typically in multiple movements."},
    { word: "ballet", hint: "A classical dance form characterized by precise and graceful movements." },
    { word: "astronaut" , hint: "A person trained to travel and work in space." },
    { word: "waterfall" , hint: "A cascade of water falling from a height." },
    { word: "technology", hint: "The application of scientific knowledge for practical purposes."},
    { word: "rainbow", hint: "A meteorological phenomenon that is caused by reflection, refraction, and dispersion of light."},
    { word:  "universe", hint: "All existing matter, space, and time as a whole."}

];
